### ISSUE TITLE
Make website mobile friendly

### ISSUE THREAD

**Issue by Abhey** [ContriHUB/Sac-Portal#2]
The landing page of sac Portal has an image gallery. Currently, images are not very responsive, Make it mobile friendly.
See here [SAC MNNIT](http://sac.mnnit.ac.in)

**Comment by darrylsepeda** [comment]
Hi @Abhey, I've created new pull request for this task, please kindly review.

**Comment by hiiiideepak** [comment]
@darrylsepeda your pr has been reviewed. Create a request on https://contrihubs.herokuapp.com/ for getting points :smile:
